added user streaming - unit tests which use env vars from helmfile - tests  - conencts to kafka  - creates topc  - sends message  - reads message from event list - base functionality to do the same thing irl - dockerfile to create

diff --git a/user-simulator/Dockerfile b/user-simulator/Dockerfile
--- a/user-simulator/Dockerfile
+++ b/user-simulator/Dockerfile
@@ -7,13 +7,16 @@ COPY . .
 # requirements.txt .
 RUN ls -l /app
 RUN ls -l /app/src
-RUN ls -l /app/src/user-simulator || echo "user_simulator not found"
+RUN ls -l /app/src/user_simulator || echo "user_simulator not found"
 
 RUN pip install --upgrade pip \
     && pip install --no-cache-dir -r requirements.txt 
 RUN pip install -e .
 
-# docker build -t user-simulator:latest .
-# awesome-plant/user-simulator:latest
+# docker build -t user_simulator:latest .
+# docker tag user_simulator:latest awesomeplant/user_simulator:latest
+# docker push awesomeplant/user_simulator:latest
+# awesomeplant/user_simulator:latest
 
 CMD ["python", "-m", "user_simulator.main"]
+
